name: flutter_ytnavigator
description: "Navigator Util."
version: 0.0.4
homepage: https://github.com/and2long/flutter_ytnavigator

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.2.1
  swipeable_page_route: ^0.4.7
  flutter_ytlog: ^0.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
